# misc
~/.tmux.conf | tmux.conf |
~/.Brewfile | Brewfile | darwin
~/.markdownlintrc | markdownlint.json |
~/.ssh/config | ssh.conf |
# config
~/.config/sway/config | config/swayconfig | linux
~/.config/gammastep/config.ini | config/gammastep.conf | linux
~/.config/waybar/config.jsonc | config/waybar/config.jsonc | linux
~/.config/foot/foot.ini | config/foot.ini | linux
~/.config/alacritty/alacritty.toml | config/alacritty.toml |
~/.config/alacritty/local-example.toml | config/alacritty-local-example.toml |
~/.config/zathura/zathurarc | config/zathurarc | linux
~/.config/ttyper/config.toml | config/ttyper.conf |
~/.config/jj/config.toml | config/jj-config.toml |
# vim
~/.vimrc | vim/vimrc |
~/.vim/functions.vim | vim/functions.vim |
~/.vim/coc-settings.json | vim/coc-settings.json |
~/.vim/spell/en.utf-8.add | vim/spell/en.utf-8.add |
# bash
~/.profile | bash/profile |
~/.bashrc | bash/bashrc |
~/.bash_aliases | bash/bash_aliases |
~/.bash_env_vars.example | bash/bash_env_vars.example |
~/.bash_aws_config | bash/bash_aws_config |
# git
~/.gitconfig | git/gitconfig |
~/.gitattributes | git/gitattributes |
~/.gitignore | git/gitignore |
~/.git-hooks/commit-msg | git/hooks/commit-msg |
~/.git-hooks/python-pre-push | git/hooks/python-pre-push |
~/.commitlintrc.json | git/commitlintrc.json |
# bin
~/.local/bin/,cc | bin/,cc |
~/.local/bin/,t | bin/,t |
~/.local/bin/,n | bin/,n |
~/.local/bin/,s | bin/,s |
~/.local/bin/,urlgrep | bin/,urlgrep |
~/.local/bin/,idle-guard | bin/,idle-guard | linux
~/.local/bin/,brew | bin/,brew | darwin
