Include ~/.ssh/config.iaction

Host git.sr.ht
    User git
    IdentityFile ~/.ssh/id_me-at-joegurr-dot-com
    PreferredAuthentications publickey

Host github.com
    User git
    IdentityFile ~/.ssh/id_me-at-joegurr-dot-com
    PreferredAuthentications publickey

Host cse
    HostName login.cse.unsw.edu.au
    User z5375985
    PubkeyAuthentication no
    RequestTTY yes

Host gitlab.cse.unsw.edu.au
    HostName gitlab.cse.unsw.edu.au
    User git
    IdentityFile ~/.ssh/id_unsw-z5375985
    PreferredAuthentications publickey

Host riesz
    HostName u648741.your-storagebox.de
    User u648741
    Port 23
    IdentityFile ~/.ssh/id_hetzner
    PreferredAuthentications publickey
