Include ~/.ssh/config.iaction
Include ~/.ssh/config.gridscout
Include ~/.ssh/config.private
Include ~/.ssh/config.unsw

Host git.sr.ht
    User git
    IdentityFile ~/.ssh/id_me-at-joegurr-dot-com
    PreferredAuthentications publickey

Host github.com
    User git
    IdentityFile ~/.ssh/id_me-at-joegurr-dot-com
    PreferredAuthentications publickey
