# 256 colors support
set -g default-terminal "screen-256color"

# sane scrolling
set -g mouse on

# CTRL+s syncs writing to panes
bind -n C-s set-window-option synchronize-panes

# wayland copying
if-shell '[ "$XDG_SESSION_TYPE" = "wayland" ]' \
    'set -g copy-command "wl-copy"'

# x11 copying
if-shell '[ "$XDG_SESSION_TYPE" = "x11" ]' \
    'set -g copy-command "xclip -selection clipboard -in"'

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

if-shell 'test "$(uname)" = Darwin' \
    'set -g @url-opener "open"' \
    'set -g @url-opener "firefox"'

# shamelessly stolen from <https://sebastiano.tronto.net/blog/2026-06-28-tmux-open-urls/>
bind u run "tmux capture-pane; tmux display-popup -E \"tmux show-buffer | $HOME/.local/bin/,urlgrep | fzf --reverse | xargs -r #{@url-opener}\""

# obvious status bar color when the focused pane is running ssh
set -g status-style "bg=#{?#{==:#{pane_current_command},ssh},red,green}"

bind r source-file ~/.tmux.conf \; display "Config reloaded!"
