# 256 colors support
set -g default-terminal "screen-256color"

# sane scrolling
set -g mouse on

# CTRL+s syncs writing to panes
bind -n C-s set-window-option synchronize-panes

# wayland copying
if-shell '[ "$XDG_SESSION_TYPE" = "wayland" ]' \
    'set -g copy-command "wl-copy"'
