# 256 colors support
set -g default-terminal "screen-256color"

# sane scrolling
set -g mouse on

# CTRL+s syncs writing to panes
bind -n C-s set-window-option synchronize-panes

# wayland copying
if-shell '[ "$XDG_SESSION_TYPE" = "wayland" ]' \
    'set -g copy-command "wl-copy"'

# x11 copying
if-shell '[ "$XDG_SESSION_TYPE" = "x11" ]' \
    'set -g copy-command "xclip -selection clipboard -in"'

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
