" vim-plug
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

call plug#begin()

" Vim HardTime
Plug 'takac/vim-hardtime'

Plug 'morhetz/gruvbox'

Plug 'neoclide/coc.nvim'

" Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
" Plug 'junegunn/fzf.vim'

call plug#end()
" :PlugInstall

" hardtime
let g:hardtime_default_on = 1
let g:hardtime_showmsg = 1

" colour scheme
set background=dark

augroup gruvbox
    autocmd vimenter * ++nested colorscheme gruvbox
augroup END

" coc
nnoremap <silent> gd <Plug>(coc-definition)
nnoremap <silent> gr <Plug>(coc-references)
nnoremap <silent> gi <Plug>(coc-implementation)
nnoremap <silent> gy <Plug>(coc-type-definition)

" You might need to run `cd ~/.vim/plugged/coc.nvim; npm ci`
" If you'd like to install a language server use this to find the right way to
" configure it: <https://github.com/neoclide/coc.nvim/wiki/Language-servers>
" python
" `npm install -g pyright`
" tex
" `cargo install --git https://github.com/latex-lsp/texlab --locked --tag <insert version here>`
" I installed v5.19.0
" html
" `:CocInstall coc-html`
" markdown
" `:CocInstall coc-markdownlint`
" c
" language server: clangd
" `sudo apt-get install clangd-12`
" as per <https://clangd.llvm.org/installation.html>
" formatter: clang-format
" `sudo apt install clang-format`
" linter/static code analysis: cppcheck
" `sudo apt install cppcheck`
" go
" lsp is gopls
" `go install golang.org/x/tools/gopls@latest`
" javascript/typescript
" `:CocInstall coc-tsserver`

set ts=4 sw=4

" Turn on spell checking
set spelllang=en_gb
set spell

" Turn on syntax highlighting.
syntax on

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number
set relativenumber

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behaviour by default.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes.
set hidden

" This setting makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if
" it contains capital letters.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nnoremap Q <Nop>

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support.
" set mouse+=a

" don't use the arrow keys!
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>

inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>

set list listchars=tab:>-,trail:.

set foldmethod=manual

set splitright
set wrap
set expandtab
set softtabstop=4

" User defined functions
source ~/.vim/functions.vim

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location
nnoremap <silent> [g <Plug>(coc-diagnostic-prev)
nnoremap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation
nnoremap <silent> gd <Plug>(coc-definition)
" nnoremap <silent> gy <Plug>(coc-type-definition)
" nnoremap <silent> gi <Plug>(coc-implementation)
" nnoremap <silent> gr <Plug>(coc-references)

" nnoremap <leader>rn <Plug>(coc-rename)
" nnoremap <leader>f  <Plug>(coc-format-selected)

" Add `:Format` command to format current buffer
" command! -nargs=0 Format :call CocActionAsync('format')

" " Add `:Fold` command to fold current buffer
" command! -nargs=? Fold :call     CocAction('fold', <f-args>)

set foldcolumn=1

" learn vimscript the hard way
let mapleader=','
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

iabbrev @@ me@joegurr.com
iabbrev adn and
" inoremap jk <esc>
" inoremap <esc> <nop>

if executable("rg")
    set grepprg=rg\ --vimgrep
endif

