#! /usr/bin/env bash

# To have this script run when committing you can copy it to
# .git/hooks/pre-commit and run chmod +x .git/hooks/pre-commit

if git grep --cached -q 'TODO'; then
    echo 'Your commit contains TODO comments. Resolve them before committing.'
    exit 1
fi

if ! nb-clean clean .; then
    echo "nb-clean failed"
    exit 1
fi

if ! pyright .; then
    echo "pyright failed"
    exit 1
fi

if ! black . --exclude '.venv,cdk.out'; then
    echo "formatting incorrect"
    exit 1
fi

if ! flake8 . --extend-exclude '.venv,cdk.out'; then
    echo "flake8 failed"
    exit 1
fi

