#! /usr/bin/env bash

# To have this script run when committing you can copy it to
# .git/hooks/pre-commit and run chmod +x .git/hooks/pre-commit

echo "python linting and formatting"

# if ! "$GLOBAL_PYTHON_VENV"/bin/pyright .; then
#     echo "pyright failed"
# fi

# if ! "$GLOBAL_PYTHON_VENV"/bin/black . --exclude '.venv,cdk.out'; then
#     echo "formatting incorrect"
# fi

# if ! "$GLOBAL_PYTHON_VENV"/bin/flake8 . --extend-exclude '.venv,cdk.out'; then
#     echo "flake8 failed"
# fi

