# dircolors sets LS_COLORS, which both ls and eza read
if test -x /usr/bin/dircolors; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# gnu grep >= 3.8 warns on the egrep/fgrep names
alias grep='grep --color=auto'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'

if command -v eza > /dev/null 2>&1; then
    alias ls='eza'
elif test -x /usr/bin/dircolors; then
    alias ls='ls --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'

# be safe
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# year of vim
alias nvim=vim

# reset terminal
alias ,reset='deactivate; cd ~; clear'

alias ,ruff='uvx ruff'
alias ,nb-clean='uvx nb-clean'
if test -n "$_bat"; then
    alias cat="$_bat -pp"
fi
alias ,eb='uvx --from awsebcli eb'
alias ,i='NOTES_DIR=$HOME/code/work/iaction/notes ,n'
alias brew=",brew"
