alias ls='eza'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'

# be safe
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# year of vim
alias nvim=vim

# reset terminal
alias ,reset='deactivate; cd ~; clear'

alias ,ruff='uvx ruff'
alias ,nb-clean='uvx nb-clean'
if command -v bat > /dev/null 2>&1; then
    alias cat='bat -pp'
fi
alias ,eb='uvx --from awsebcli eb'
alias ,i="NOTES_DIR=/home/joe/code/work/iaction/notes ,n"
alias brew=",brew"
