alias ls='eza'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'

# be safe
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# year of vim
alias nvim=vim
# alias code=vim

# reset terminal
alias ,reset='deactivate; cd ~; clear'

alias black='$GLOBAL_PYTHON_VENV/bin/black --extend-exclude "\(\.venv|cdk.out\)"'
alias flake8='$GLOBAL_PYTHON_VENV/bin/flake8 --extend-exclude ".venv, cdk.out" --max-line-length 88'
alias ruff='$GLOBAL_PYTHON_VENV/bin/ruff'
alias nb-clean='$GLOBAL_PYTHON_VENV/bin/nb-clean'
alias bat='batcat -pp'
alias cat='bat'
alias eb='uvx --from awsebcli eb'
alias ,i="NOTES_DIR=/home/joe/code/work/iaction/notes ,n"
